language: python

python:
  - "3.9"

dist: jammy

install:
  - pip install -r requirements.txt

stages:
  - static analysis
  - test

env:
  global:
    - FLASK_APP=main.py

jobs:
  include:
    - stage: static analysis
      name: "pylint"
      script: make lint
    - stage: test
      name: "pytest"
      script: make test
